# Generated by Django 2.2.13 on 2020-06-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(default='DEFAULT VALUE', max_length=250),
        ),
    ]
